readonlyrest:
  prompt_for_basic_auth: false
  audit_collector: true
  access_control_rules:
    - name: "CONTAINER ADMIN"
      verbosity: error
      type: allow
      auth_key: admin:container

    - name: "test1"
      indices: ["test1_index", "test1_index_reindexed"]
      auth_key: dev1:test
